[project]
name = "app"
version = "0.1.0"
description = "CNN para la evaluación de exámenes de tipo alveolo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imutils>=0.5.4",
    "keras>=3.14.1",
    "opencv-python-headless>=4.13.0.92",
    "pydantic-settings>=2.14.1",
    "tensorflow>=2.21.0",
]

[dependency-groups]
dev = ["matplotlib>=3.10.9", "scikit-learn>=1.8.0", "ty>=0.0.35"]
